Perform a preflight check to ensure that we have readlink or greadlink, exiting with failure if we don't.
readlink comes from GNU coreutils.  On systems without it, rbenv used to
spin out of control when it didn't have readlink or greadlink available
because it would re-exec the frontend script over and over instead of the
worker script in libexec.

Resolves issue #389

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -12,8 +12,16 @@ if [ -n "$RBENV_DEBUG" ]; then
   set -x
 fi
 
+precheck() {
+  READLINK=$(type -p greadlink readlink | head -1)
+  if [ -z "$READLINK" ]; then
+    echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+    exit 1
+  fi
+}
+
 resolve_link() {
-  $(type -p greadlink readlink | head -1) "$1"
+  $READLINK "$1"
 }
 
 abs_dirname() {
@@ -49,6 +57,7 @@ else
 fi
 export RBENV_DIR
 
+precheck
 
 shopt -s nullglob
 
@@ -65,7 +74,6 @@ done
 export RBENV_HOOK_PATH="$hook_path"
 
 shopt -u nullglob
-
 
 command="$1"
 case "$command" in
