Move readlink check inline. Replicate readlink check into rbenv-hooks and rbenv-init as well.

diff --git a/libexec/rbenv b/libexec/rbenv
--- a/libexec/rbenv
+++ b/libexec/rbenv
@@ -12,14 +12,6 @@ if [ -n "$RBENV_DEBUG" ]; then
   set -x
 fi
 
-precheck() {
-  READLINK=$(type -p greadlink readlink | head -1)
-  if [ -z "$READLINK" ]; then
-    echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
-    exit 1
-  fi
-}
-
 resolve_link() {
   $READLINK "$1"
 }
@@ -57,7 +49,11 @@ else
 fi
 export RBENV_DIR
 
-precheck
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
 
 shopt -s nullglob
 
diff --git a/libexec/rbenv-hooks b/libexec/rbenv-hooks
--- a/libexec/rbenv-hooks
+++ b/libexec/rbenv-hooks
@@ -20,7 +20,7 @@ if [ -z "$RBENV_COMMAND" ]; then
 fi
 
 resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
+  $READLINK "$1"
 }
 
 realpath() {
@@ -38,6 +38,12 @@ realpath() {
 }
 
 IFS=: hook_paths=($RBENV_HOOK_PATH)
+
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
 
 shopt -s nullglob
 for path in "${hook_paths[@]}"; do
diff --git a/libexec/rbenv-init b/libexec/rbenv-init
--- a/libexec/rbenv-init
+++ b/libexec/rbenv-init
@@ -26,7 +26,7 @@ if [ -z "$shell" ]; then
 fi
 
 resolve_link() {
-  $(type -p greadlink readlink | head -1) $1
+  $READLINK "$1"
 }
 
 abs_dirname() {
@@ -42,6 +42,12 @@ abs_dirname() {
   pwd
   cd "$cwd"
 }
+
+READLINK=$(type -p greadlink readlink | head -1)
+if [ -z "$READLINK" ]; then
+  echo "rbenv: cannot find readlink - are you missing GNU coreutils?" >&2
+  exit 1
+fi
 
 root="$(abs_dirname "$0")/.."
 
